# -*- coding: utf-8 -*-
"""Copy of EDA Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgysOX-s1483rnuCGwNL9MpfzZ0kgc2o
"""

# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
# %matplotlib inline

df=pd.read_excel('/Automobile.xlsx')
df.head()

df.shape

df.info()

df.describe()

dups=df.duplicated()
print('Number of duplicate rows = %d' % (dups.sum()))
df[dups]

df.boxplot(column=['mpg'])
plt.show()

df.boxplot(column=['acceleration'])
plt.show()

df.boxplot(column=['horsepower'])
plt.show()

def remove_outlier(col):
  sorted(col)
  Q1,Q3=col.quantile([0.25,0.75])
  IQR=Q3-Q1
  lower_range=Q1-(1.5*IQR)
  upper_range=Q3+(1.5*IQR)
  return lower_range,upper_range

lrmpg,urmpg=remove_outlier(df['mpg'])
df['mpg']=np.where(df['mpg']>urmpg,urmpg,df['mpg'])
df['mpg']=np.where(df['mpg']<lrmpg,lrmpg,df['mpg'])

lracceleration,uracceleration=remove_outlier(df['acceleration'])
df['acceleration']=np.where(df['acceleration']>uracceleration,uracceleration,df['acceleration'])
df['acceleration']=np.where(df['acceleration']<lracceleration,lracceleration,df['acceleration'])

lrhorsepower,urhorsepower=remove_outlier(df['horsepower'])
df['horsepower']=np.where(df['horsepower']>urhorsepower,urhorsepower,df['horsepower'])
df['horsepower']=np.where(df['horsepower']<lrhorsepower,lrhorsepower,df['horsepower'])

df.shape

df.boxplot(column=['mpg'])
plt.show()

df.boxplot(column=['acceleration'])
plt.show()

df.boxplot(column=['horsepower'])
plt.show()

#no missing values
df.isnull().sum()

sns.distplot(df.mpg,bins=20)

sns.countplot(x="cylinders",hue="mpg",data=df)

sns.pairplot(df)
plt.show()

df_numeric = df.drop(['name', 'origin'], axis=1)
df_numeric.corr()

plt.figure(figsize=(10,10))
sns.heatmap(df_numeric.corr(),annot=True,fmt='.2f',cmap='Blues')
plt.show()

dummies=pd.get_dummies(df[["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year"]],columns=["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year"],prefix=["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year"],drop_first=True).head()

columns=["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year"]
df = pd.concat([df,dummies],axis=1)
df.drop(columns,axis=1,inplace=True)

df.head()